apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver-deploy
  name: resultserver-deploy
spec:
  imagePullSecrets:
  - name: regcred
  replicas: 1
  selector:
    matchLabels:
      app:  resultserver-deploy
  template:
    metadata:
      labels:
        app: resultserver-deploy
    spec:
      containers:
      - image: 556625583567.dkr.ecr.us-east-1.amazonaws.com/phonebook-jo/result
        name: resultserver
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: mysql-secret
          - configMapRef:
              name: server-config
        resources: {}
